<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-7DIC8F6" name="dominoFramework.test.CreatePizzaProfileTest" tests="3" failures="2" timestamp="18 Jan 2018 01:53:18 GMT" time="35.111" errors="0">
  <testcase name="enterBothEmailFields" time="13.044" classname="dominoFramework.test.CreatePizzaProfileTest"/>
  <testcase name="enterEmail" time="6.622" classname="dominoFramework.test.CreatePizzaProfileTest">
    <failure type="java.lang.AssertionError" message="expected:&lt;That email is totally wrong and so is this.&gt; but was:&lt;Please enter a valid email address.&gt;">
      <![CDATA[java.lang.AssertionError: expected:<That email is totally wrong and so is this.> but was:<Please enter a valid email address.>at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)at dominoFramework.test.CreatePizzaProfileTest.enterEmail(CreatePizzaProfileTest.java:62)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.lang.Thread.run(Unknown Source)]]>
    </failure>
  </testcase> <!-- enterEmail -->
  <testcase name="enterFirstName" time="15.445" classname="dominoFramework.test.CreatePizzaProfileTest">
    <failure type="java.lang.AssertionError" message="expected:&lt;Bob&gt; but was:&lt;&gt;">
      <![CDATA[java.lang.AssertionError: expected:<Bob> but was:<>at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)at dominoFramework.test.CreatePizzaProfileTest.enterFirstName(CreatePizzaProfileTest.java:39)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.lang.Thread.run(Unknown Source)]]>
    </failure>
  </testcase> <!-- enterFirstName -->
</testsuite> <!-- dominoFramework.test.CreatePizzaProfileTest -->
